services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 111
      POSTGRES_DB: Advertisements
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U"]
